name: "mpc-cbf"

services:
  dev-container:
    image: wangyt163/mpc-cbf:latest
    stdin_open: true
    tty: true
    volumes:
      - ../workspace:/usr/src/mpc-cbf/workspace
      - ../.git:/usr/src/mpc-cbf/.git
